import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Portfolio - Rafael Brito</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
      <div >
          <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
            <Navbar />
          {children}
        </main>
      </div>
      </body>
    </html>
  )
}
